### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by OMGerEDU** [ScriptLabs-AI/RobloxScripterAI#2]
I ran the Readme, And I wrote "Create RPG Game"
Did not work.

**Comment by asaxena1415** [comment]
Hey there, this is too broad of a question to ask scripterAI, it's not currently capable of creating the entire game, you'll need to be more specific about what you want, for example, if it's a quest in your RP game, then you can ask the scripterAI to create functions for that quest, hope it helps, I'll add to our doc as well 👍
